site_name: sofia documentation
site_url: https://qasterr.github.io/sofia/
nav:
  - Home: index.md
  - Courses: courses.md
  - Dependencies: dependencies.md
theme:
  name: readthedocs
  highlightjs: true