site_name: sofia documentation
site_url: https://qasterr.github.io/sofia/
nav:
  - Home: index.md
  - Courses: courses.md
  - Dependencies: dependencies.md
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode