site_name: sofia documentation
site_url: https://sofia-docs.readthedocs.io/
nav:
  - Home: index.md
  - Courses: courses.md
  - Dependencies: dependencies.md
theme:
  name: readthedocs
  highlightjs: true